In [ ]:
# Lists ( Ordered, Mutable and Allows Duplicates)
# Use Cases - To Do List, Shopping Cart

fruits = ["apple","banana","mango"]
fruits.append("orange")
fruits[1]="kiwi"
print(fruits)


['apple', 'kiwi', 'mango', 'orange']


In [ ]:
# Tuple ( Ordered, Immutable and allows duplicates)
# Use Cases - Coordinates of GPS Data, Date and Time, Database rows

coords = (4,5)
print(coords[0])

4


In [ ]:
# Set ( Unordered, No Duplicates and Mutable)
# Use Cases - Unqiue Tags or labels ( hastag in a post), Union, Intersection

fruits_set = {"cat","dog","dog","bird"}
print(fruits_set)

{'dog', 'cat', 'bird'}


In [ ]:
# Dictionary 
# Use Cases - Storing User Profiles, API Response Data, Configuration Settings


student = {
    "name":"Shashank",
    "age":22
}

print(student['age'])

22


In [ ]:
# Conditionals

score = 85
if score >= 90:
    print("Excellent")
elif score >= 70:
    print("Good")               
else:
    print("Needs improvement")


Good


In [ ]:
# Loops
for i in range(5):
    print(i)

for i in range(0,10):
    print(i)
    
    
a=5
while a>0:  #If the condition is true, not if the condition is gonna be true
    print(a)
    a = a-1

5
4
3
2
1


In [17]:
# Functions ( args, kwargs and lambda)

def greet(name):
    print(f"Hey {name}")
    
greet("Shashank")


# Takes any number of positional arguments
def add_all(*args):
    return sum(args)


print(add_all(1,2,2,35,5,6,6,6))


# Takes any number of keyword arguments

def describe_person(**kwargs):
    for key,value in kwargs.items():
        print(f"{key}:{value}")
        
describe_person(name="Shashank",Age=30)


# Lambda - Anonymous one line functions

square = lambda x:x**2
print(square(5))


Hey Shashank
63
name:Shashank
Age:30
25


In [24]:
# OOP


# Class, Attribute and Methods
class Car:
    def __init__(self,brand,color,speed):
        self.brand = brand
        self.color = color
        self.speed = speed
        
    def accelerate(self):
        self.speed +=10
        return self.speed
    

car1= Car("Toyota","Green",110)
print(car1.accelerate())

# Inheritance

class ElectricCar(Car):
    def __init__(self, brand, color, speed, battery):
        super().__init__(brand, color, speed)
        self.battery = battery
        

car2 = ElectricCar("Tesla","Black",50,"5000MaH")
print(car2.accelerate())


# Encapsulation

class Account:
    def __init__(self,balance):
        self._balance = balance
    def deposit(self,amount):
        self._balance +=amount
        print(f"Amount Deposited: {amount}")
        print(f"Total Balance: {self._balance}")
        
acc1 = Account(5000)
acc1.deposit(500)

120
60
Amount Deposited: 500
Total Balance: 5500


In [25]:
# Modules and Imports

import math
print(math.sqrt(16))            # 4.0

import os
print(os.getcwd())              # Current working directory

import random
print(random.randint(1, 10))    # Random integer between 1 and 10


4.0
e:\Python
4


In [ ]:
# Libraries for Data Science and ML - Numpy, Pandas, Matplotlib, Seaborn

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("data.csv")
print(df.head())

sns.histplot(df['Age'])
plt.show()


In [6]:
string = "Shashank"
string2 = ""
for i in range(len(string)-1,-1,-1):
    string2 += string[i]

print(string2)

knahsahS


In [8]:
string = "madam"
string2 = string[::-1]
if string==string2:
    print("Yes")
else:
    print("No")

Yes


In [14]:
def find_max(list1):
    return max(list1)


def find_max2(list1):
    maxNum=list1[0]
    for i in range(1,len(list1)):
        if list1[i]>maxNum:
            maxNum=list1[i]
    return maxNum

print(find_max([1,2,3,4,5,8]))
print(find_max2([1,2,3,4,5,8]))



8
8


In [16]:
def count_vowels(string1):
    count=0
    for i in range(0,len(string1)):
        if string1[i]=="a" or string1[i]=="e" or string1[i]=="i" or string1[i]=="o" or string1[i]=="u":
            count+=1
    return count

def count_vowels2(string1):
    vowels = "aeiouAEIOU"
    return sum(1 for char in string1 if char in vowels)

print(count_vowels("hello world"))
print(count_vowels2("hello world"))

3
3


In [21]:
def two_sum(nums, target):
    for i in range(0,len(nums)):
        for j in range(i+1,len(nums)):
            if nums[i]+nums[j] == target:
                return [i,j]
            

    return [-1,-1]




def two_sum2(nums, target):
    seen = {}
    for i, num in enumerate(nums):
        diff = target - num
        if diff in seen:
            return [seen[diff],i]
        seen[num] = i


arr = [2, 7, 11, 15]
target = 26

print(two_sum(arr,target))
print(two_sum2(arr,target))


[2, 3]
[2, 3]


In [26]:
def fizzbuzz(num):
    if num%3==0 and num%5==0:
        print("FizzBuzz")
    elif num%3==0:
        print("Fizz")
    elif num%5==0:
        print("Buzz")

fizzbuzz(100)

Buzz


In [30]:
def duplicates(nums):
    duplicates = []
    for i in range(0,len(nums)):
        for j in range(i+1, len(nums)):
            if nums[i]==nums[j] and nums[i] not in duplicates:
                duplicates.append(nums[i])
    
    return duplicates


def duplicates2(nums):
    duplicates = {}
    
    for num in nums:
        duplicates[num] = duplicates.get(num,0)+1
        
    
    return duplicates



print(duplicates([1,2,3,5,4,4,5,6]))
print(duplicates2([1,2,3,5,4,4,5,6]))
                

[5, 4]
{1: 1, 2: 1, 3: 1, 5: 2, 4: 2, 6: 1}


In [37]:
# Sort a List

def sortList(nums):
    nums.sort()
    return nums

def sortList2(nums):
    for i in range(len(nums)):
        already_sorted = True
        
        for j in range(len(nums)-i-1):
            if nums[j]>nums[j+1]:
                nums[j],nums[j+1]=nums[j+1],nums[j]
                already_sorted = False
        if already_sorted:
            break
    return nums
        

print(sortList([0,6,2,3,1]))
print(sortList2([0,6,2,3,1]))

[0, 1, 2, 3, 6]
[0, 1, 2, 3, 6]


In [40]:
from collections import Counter

def word_frequency(string1):
    words = string1.lower().split()
    return dict(Counter(words))


def word_frequency2(string1):
    words = string1.lower().split()
    duplicates = {}
    
    for word in words:
        duplicates[word] =  duplicates.get(word,0)+1
    
    return duplicates

print(word_frequency("the quick brown fox jumps over the lazy dog the dog slept"))
print(word_frequency2("the quick brown fox jumps over the lazy dog the dog slept"))


{'the': 3, 'quick': 1, 'brown': 1, 'fox': 1, 'jumps': 1, 'over': 1, 'lazy': 1, 'dog': 2, 'slept': 1}
{'the': 3, 'quick': 1, 'brown': 1, 'fox': 1, 'jumps': 1, 'over': 1, 'lazy': 1, 'dog': 2, 'slept': 1}


In [54]:
import string
alphabets = string.ascii_lowercase

def isPangram(text):
    text = text.lower()
    for i in alphabets:
        if i  not in text:
            return "No"
    
    
    return "Yes"

print(isPangram("The quick brown fox jumps over the lazy dog"))

Yes


In [58]:
import string
alphabets = string.ascii_lowercase

def isPangram(text):
    isPanagram = True
    missingLetters = []
    text = text.lower()
    for i in alphabets:
        if i  not in text:
            isPanagram = False
            if(isPanagram==False):
                missingLetters.append(i)

    if(isPanagram):
        return "Yes"
    
    print(missingLetters)
    return "No"

print(isPangram("The quick brown fox jumps over the lazy dog"))

Yes


In [59]:
# Creating a 3x3 matrix using nested lists
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(matrix)
# Output: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Accessing elements: matrix[row][column]
print(matrix[0][1])  # Output: 2 (first row, second column)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
2


In [60]:
import numpy as np

# Create matrices using NumPy
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix1)

# Create special matrices
zeros_matrix = np.zeros((3, 3))
ones_matrix = np.ones((2, 4))
identity_matrix = np.eye(3)
random_matrix = np.random.randint(1, 10, size=(3, 3))

print("Zeros matrix:")
print(zeros_matrix)
print("Identity matrix:")
print(identity_matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Zeros matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
